meta:
  type: llm
  work_dir: ./logs

model:
  type: Qwen3
  model_path: Qwen/Qwen3-30B-A3B
  model_hub: hf
  model_kwargs:
    trust_remote_code: true
    low_cpu_mem_usage: true
    use_cache: false
    torch_dtype: auto
    device_map: cpu
  tokenizer_kwargs:
    trust_remote_code: true

calib_dataset:
  dataset:
    type: TextDataset
    data_path: ./dataset/sharegpt_gpt4_qwen/sharegpt_gpt4-qwen3_a22B_output.jsonl
    num_samples: 128
    max_seq_length: 4096
  dataloader:
    batch_size: 1
    shuffle: true
    num_workers: 0

pipeline:
  - type: ptq
    algo_name: GPTQ
    ignore_layers: []
    algo_config:
      w_bits: 4

  - type: save
    algo_name: HuggingFaceSaver
    save_dir: ./outputs
