[project]
name = "npuslim"
version = "0.0.0.dev"
description = "NPU oriented model compression & quantization framework"
authors = [{ name = "PCL authors", email = "xxx@xxx.com" }]
readme = "README.md"
requires-python = ">=3.11"
license = { text = "Apache-2.0" }

dependencies = [
    "rich",
    "loguru",
    "easydict",
    "dacite",
    "threadpoolctl",
    "datasets",
    "transformers<5.0.0",
    "lm-eval",
    "evalscope",
    "optimum",
    "primefac"
]

[project.scripts]
npuslim = "npuslim.cli.__main__:main"

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = ["sitecustomize"]

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points."vllm.general_plugins"]
npuslim = "npuslim.plugins:register"

[project.entry-points."transformers.quantizers"]
quip = "npuslim.plugins.transformers.quantizers.quantizer_quip:QuipHfQuantizer"