[project]
name = "npuslim"
version = "0.0.0.dev"
description = "NPU oriented model compression & quantization framework"
authors = [{ name = "PCL authors", email = "xxx@xxx.com" }]
readme = "README.md"
requires-python = ">=3.11"
license = { text = "Apache-2.0" }

dependencies = [
    "torch==2.8.0",
    # "torch-npu==2.7.1",
    # "vllm==0.11.0",
    # "vllm_ascend>0.11.0rc1",
    "rich",
    "loguru",
    "easydict",
    "dacite",
    "datasets",
    "accelerate",
    "transformers",
]

[project.scripts]
npuslim = "npuslim.cli.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points."vllm.general_plugins"]
register_npuslim = "npuslim.vllm_plugin:register"
