meta:
  type: llm
  work_dir: ./logs

model:
  type: Qwen3
  model_path: Qwen/Qwen3-0.6B
  model_hub: hf
  model_kwargs:
    trust_remote_code: true
    low_cpu_mem_usage: true
    use_cache: false
    torch_dtype: auto
    device_map: cpu
  tokenizer_kwargs:
    trust_remote_code: true

pipeline:
  - type: eval
    output_dir: ./outputs
    datasets: [ wikitext ]
    num_fewshot: 0
    batch_size: 1
    limit: null