#  configuration of pipeline
meta:
  type: llm
  save_path: ./outputs

# Simplified Configuration for LLM compression
model:
  type: Qwen3
  model_path: Qwen/Qwen3-32B
  model_hub: ms  # ms (modelscope) or hf (huggingface)
  model_kwargs:
    trust_remote_code: true
    low_cpu_mem_usage: true
    use_cache: false
    torch_dtype: auto
    device_map: cpu

# Dataset for calibration
calib_dataset:
  dataset:
    type: TextDataset
    data_path: ./dataset/sharegpt_gpt4_qwen/sharegpt_gpt4-qwen3_a22B_output.jsonl
    num_samples: 128
    max_seq_length: 4096
  dataloader:
    batch_size: 1
    shuffle: true
    num_workers: 0

# Post-Training Quantization
ptq:
  type: WXAX
  quant_config:
    w_bits: 8
    a_bits: 8
    w_symm: true    # 对称量化
    a_symm: false
    w_signed: true  # 符号量化
    a_signed: true
    quant_weight: "per-channel"  # per-channel or per-tensor
  ignore_layers: []