#  configuration of pipeline
meta:
  type: llm
  save_path: ./outputs

# Simplified Configuration for LLM compression
model:
  type: Qwen3
  model_path: Qwen/Qwen3-4B-Instruct-2507
  model_hub: ms  # ms (modelscope) or hf (huggingface)
  model_kwargs:
    trust_remote_code: true
    low_cpu_mem_usage: true
    use_cache: false
    torch_dtype: auto
    device_map: cpu
  tokenizer_kwargs:
    trust_remote_code: true

# Dataset for calibration
calib_dataset:
  dataset:
    type: TextDataset
    data_path: ./dataset/sharegpt_gpt4_qwen/sharegpt_gpt4-qwen3_a22B_output.jsonl
    num_samples: 128
    max_seq_length: 4096
  dataloader:
    batch_size: 1
    shuffle: true
    num_workers: 0

# Sparse
sparse:
  type: SparseGPT
  sparse_config:
    sparsity_ratio: 0.5
    pattern: "2:4"
    algo_params:
      blocksize: 128
      percdamp: 0.01
  ignore_layers: 
    - 'lm_head'

