meta:
  type: llm
  work_dir: ./logs

model:
  type: OPT
  model_path: facebook/opt-125m
  model_hub: hf
  model_kwargs:
    trust_remote_code: true
    low_cpu_mem_usage: true
    use_cache: false
    torch_dtype: auto
    device_map: cpu
  tokenizer_kwargs:
    trust_remote_code: true

calib_dataset:
  dataset:
    type: C4Dataset
    num_samples: 128
    max_seq_length: 2048
    seed: 0
  dataloader:
    batch_size: 1
    shuffle: true
    num_workers: 0

pipeline:
  - type: ptq
    algo_name: GPTQ
    ignore_layers: 
      - model.decoder.layers.11.*
      - model.decoder.layers.12.*
    algo_config:
      w_bits: 4

  # - type: eval

  - type: save
    algo_name: AscendSaver
    save_dir: ./outputs
    saver_args:
      strip_quant_config: true
