meta:
  type: llm
  work_dir: ./logs

model:
  type: OPT
  model_path: facebook/opt-125m
  model_hub: hf
  model_kwargs:
    trust_remote_code: true
    low_cpu_mem_usage: true
    use_cache: false
    torch_dtype: auto
    device_map: cpu
  tokenizer_kwargs:
    trust_remote_code: true

calib_dataset:
  dataset:
    type: C4Dataset
    num_samples: 128
    max_seq_length: 2048
    seed: 0
  dataloader:
    batch_size: 1
    shuffle: true
    num_workers: 0

pipeline:
  - type: sparse
    algo_name: SparseGPT
    ignore_layers: ["lm_head"]
    algo_config:
      sparsity: 0.5
      prunen: 0
      prunem: 0
      blocksize: 128
      percdamp: 0.01

  - type: save
    algo_name: HuggingFaceSaver
    save_dir: ./outputs
